# https://aka.ms/yaml

jobs:

- job: runtime
  pool:
    vmImage: 'Ubuntu-latest'
  steps:
  - script:
      cmake -E make_directory cmake-build
    displayName: 'Creating build directory'
  - script:
      sudo apt install ninja-build texinfo autopoint -y
    displayName: 'Installing dependencies'
  - script:
      cmake -E chdir cmake-build
      cmake ..
      -GNinja
      -DCMAKE_TOOLCHAIN_FILE=../cmake/MeToolchain.cmake
      -DWIMAL_TARGET=x64-linux
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_INSTALL_PREFIX="$(Build.BinariesDirectory)/$(Agent.JobName)"
    displayName: 'Configuring'
  - script:
      cmake -E env VERBOSE=1 NO_DBG=1 ALL=1 EXT=1 cmake --build cmake-build --target strip-all --
    displayName: 'Building'
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)/$(Agent.JobName)'
      includeRootFolder: true
      archiveType: 'tar'
      tarCompression: 'xz'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Agent.JobName)-$(Build.BuildNumber).tar.xz'
      replaceExistingArchive: true
    displayName: 'Creating tarball'
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: '$(Agent.JobName)-$(Build.BuildNumber)'
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Uploading'
